//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalNugetManager {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2016-01-01")]
        public global::System.DateTime LastVersionCheck {
            get {
                return ((global::System.DateTime)(this["LastVersionCheck"]));
            }
            set {
                this["LastVersionCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FirstRun {
            get {
                return ((bool)(this["FirstRun"]));
            }
            set {
                this["FirstRun"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\LocalNugetManager\\LocalNugetManager_versions.txt")]
        public string RemoteVersionPath {
            get {
                return ((string)(this["RemoteVersionPath"]));
            }
            set {
                this["RemoteVersionPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\LocalNugetManager\\LocalNugetManager.vsix")]
        public string RemoteVsixPath {
            get {
                return ((string)(this["RemoteVsixPath"]));
            }
            set {
                this["RemoteVsixPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\LocalNugetManager\\LocalNugetManager_beta.vsix")]
        public string RemoteVsixPath_Beta {
            get {
                return ((string)(this["RemoteVsixPath_Beta"]));
            }
            set {
                this["RemoteVsixPath_Beta"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BetaChannelUpdate {
            get {
                return ((bool)(this["BetaChannelUpdate"]));
            }
            set {
                this["BetaChannelUpdate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\NugetLocal")]
        public string LocalFolderForRepository {
            get {
                return ((string)(this["LocalFolderForRepository"]));
            }
            set {
                this["LocalFolderForRepository"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int DelayBetweenSynchronizationInMinute {
            get {
                return ((int)(this["DelayBetweenSynchronizationInMinute"]));
            }
            set {
                this["DelayBetweenSynchronizationInMinute"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoSynchronize {
            get {
                return ((bool)(this["AutoSynchronize"]));
            }
            set {
                this["AutoSynchronize"] = value;
            }
        }
    }
}
